// What a tool declares about itself. An agent is a tool.
//
// This file is deliberately almost empty, and growing it has a rule: **a field
// arrives when the thing that enforces it arrives, never before.** An audit of
// the estate this replaces traced every field of its tool and agent options to
// an enforcer and found five declared and enforced by nothing -- including one
// whose own comment admitted it was "parsed by lint, not evaluated", and a whole
// instance-authorization vocabulary with no implementation. None of it was
// carelessness; each was added in good faith slightly ahead of its enforcer and
// nothing ever checked the gap. The gap is what this file refuses to open.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/tool/v1/tool.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool's ONE identity. Policy keys on it, logs name it, allowlists cite
	// it, tokens carry it.
	//
	// THE METHOD'S PROTO FULL NAME IS AN ADDRESS, NEVER AN IDENTITY. That sentence
	// is the whole point of this field and the direct fix for the two most
	// expensive bugs in the estate this replaces: an agent had a short declared
	// name AND a proto full name, both were used as identity in different places,
	// and twice a component passed one where another expected the other. Each time
	// the symptom was a refusal with a correct-looking message and a cause three
	// services away.
	//
	// One spelling. If you hold `testdata.v1.SupportAssistantService.Invoke` and
	// something wants a tool, you hold an address and must look up the name. If
	// you are tempted to add a second identity field, that is this bug returning.
	//
	// Explicit rather than derived from the method path, because an identity
	// derived from a path changes when the path does, and then every policy that
	// keys on it silently stops matching. Uniqueness therefore needs a lint rule,
	// which arrives with the linter.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// HOW THIS TOOL IS ANSWERED, and the whole of what an "agent" is.
	//
	// Absent: a service answers the call itself. A balance lookup, a payment.
	// Present: a RUNNER answers it, and this says what that run may call in turn.
	//
	// This replaces a split that cost the previous estate real money. There, a
	// tool option sat on each method and a separate AGENT option sat on the
	// service, at a different level, with its own identity -- and the two had to
	// be kept consistent by a lint rule (A5, `lintAgentDoorParity`) that existed
	// for no other reason. Meanwhile an agent already appeared in other agents'
	// allowlists as a plain tool name, so the model was half-unified in practice
	// and fully split in the contract.
	//
	// The distinction that actually matters is not tool-versus-agent. It is **who
	// answers this call** -- a service, or the platform. That is one optional
	// field, not two option types at two attachment levels.
	Agent         *Agent `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// What rund runs when a tool declares one.
//
// NOTE WHAT IS ABSENT: no field names WHICH IMPLEMENTATION decides this agent's
// steps -- DBOS or Temporal, react-v2 or react-experimental. That is a
// deployment's topology, settled by rund's own routing table, and a tool author
// who could name it would be choosing somebody else's deployment.
//
// A field naming the KIND -- ReAct, Workflow -- will arrive when a decider does,
// because by then it has readers: compose can refuse a Workflow declaring no
// steps, and a declared kind can be reconciled against what is actually serving.
// It is absent today for the reason at the top of this file, and for no other.
type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What a run may call, and the only thing currently enforced.
	//
	// THE ALLOWLIST IS THE ONLY AUTHORITY on what a run may call. Nothing widens
	// it -- not a prompt, not a graph, not a runtime decision. When something that
	// orders calls arrives, it will be able to order only what is already here.
	//
	// Entries name tools by `Tool.name`, the same spelling a tool declares for
	// itself. One namespace: an agent in another agent's allowlist is an ordinary
	// entry, because an agent is an ordinary tool.
	Tools         []*ToolRef `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *Agent) GetTools() []*ToolRef {
	if x != nil {
		return x.Tools
	}
	return nil
}

// One entry in an allowlist.
//
// A message rather than a bare string, so this grows without a breaking change:
// a guard, a per-tool ceiling, a rate can each arrive as a field when its
// enforcer does. It carries a name and nothing else today, on purpose -- the
// message exists so the NEXT thing has somewhere to go, not so fields can be
// declared ahead of the code that honours them.
type ToolRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool, by its declared `Tool.name`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRef) Reset() {
	*x = ToolRef{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRef) ProtoMessage() {}

func (x *ToolRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRef.ProtoReflect.Descriptor instead.
func (*ToolRef) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *ToolRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_garm_tool_v1_tool_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Tool)(nil),
		Field:         50002,
		Name:          "garm.tool.v1.tool",
		Tag:           "bytes,50002,opt,name=tool",
		Filename:      "garm/tool/v1/tool.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional garm.tool.v1.Tool tool = 50002;
	E_Tool = &file_garm_tool_v1_tool_proto_extTypes[0]
)

var File_garm_tool_v1_tool_proto protoreflect.FileDescriptor

const file_garm_tool_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x17garm/tool/v1/tool.proto\x12\fgarm.tool.v1\x1a google/protobuf/descriptor.proto\"E\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x05agent\x18\x02 \x01(\v2\x13.garm.tool.v1.AgentR\x05agent\"4\n" +
	"\x05Agent\x12+\n" +
	"\x05tools\x18\x01 \x03(\v2\x15.garm.tool.v1.ToolRefR\x05tools\"\x1d\n" +
	"\aToolRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:H\n" +
	"\x04tool\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\v2\x12.garm.tool.v1.ToolR\x04toolB0Z.github.com/garm-ai/garm-ai/garm/tool/v1;toolv1b\x06proto3"

var (
	file_garm_tool_v1_tool_proto_rawDescOnce sync.Once
	file_garm_tool_v1_tool_proto_rawDescData []byte
)

func file_garm_tool_v1_tool_proto_rawDescGZIP() []byte {
	file_garm_tool_v1_tool_proto_rawDescOnce.Do(func() {
		file_garm_tool_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_tool_v1_tool_proto_rawDesc), len(file_garm_tool_v1_tool_proto_rawDesc)))
	})
	return file_garm_tool_v1_tool_proto_rawDescData
}

var file_garm_tool_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_garm_tool_v1_tool_proto_goTypes = []any{
	(*Tool)(nil),                       // 0: garm.tool.v1.Tool
	(*Agent)(nil),                      // 1: garm.tool.v1.Agent
	(*ToolRef)(nil),                    // 2: garm.tool.v1.ToolRef
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
}
var file_garm_tool_v1_tool_proto_depIdxs = []int32{
	1, // 0: garm.tool.v1.Tool.agent:type_name -> garm.tool.v1.Agent
	2, // 1: garm.tool.v1.Agent.tools:type_name -> garm.tool.v1.ToolRef
	3, // 2: garm.tool.v1.tool:extendee -> google.protobuf.MethodOptions
	0, // 3: garm.tool.v1.tool:type_name -> garm.tool.v1.Tool
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_garm_tool_v1_tool_proto_init() }
func file_garm_tool_v1_tool_proto_init() {
	if File_garm_tool_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_tool_v1_tool_proto_rawDesc), len(file_garm_tool_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_garm_tool_v1_tool_proto_goTypes,
		DependencyIndexes: file_garm_tool_v1_tool_proto_depIdxs,
		MessageInfos:      file_garm_tool_v1_tool_proto_msgTypes,
		ExtensionInfos:    file_garm_tool_v1_tool_proto_extTypes,
	}.Build()
	File_garm_tool_v1_tool_proto = out.File
	file_garm_tool_v1_tool_proto_goTypes = nil
	file_garm_tool_v1_tool_proto_depIdxs = nil
}
