// What an agent declares about itself.
//
// This file is deliberately almost empty, and growing it has a rule: **a field
// arrives when the thing that enforces it arrives, never before.** The estate
// this replaces had eleven fields on its agent options, of which one shipped
// admitting in its own comment that it was "parsed by lint, not evaluated", and
// four more in the tool options turned out to have no enforcer at all. A
// declaration nothing acts on is not documentation -- it is a promise the
// platform breaks silently, and a reader has no way to tell which promises hold.
//
// So: one field, one enforced property, and the next field waits its turn.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent's ONE identity. Policy keys on it, logs name it, tokens carry it.
	//
	// THE SERVICE'S PROTO FULL NAME IS AN ADDRESS, NEVER AN IDENTITY. That
	// sentence is the whole point of this field, and it is the direct fix for the
	// two most expensive bugs in the system this replaces: an agent had both a
	// short declared name and a proto full name, both were used as identity in
	// different places, and twice a component passed one where another expected
	// the other. Each time the symptom was a refusal with a correct-looking
	// message and a cause three services away.
	//
	// So there is exactly one spelling. If you are holding
	// `bank.agents.v1.SupportAssistant` and something wants an agent, you are
	// holding an address and you need to look up the name. If you are tempted to
	// add a second identity field, that is this bug returning.
	//
	// An explicit name rather than deriving it from the service name, because an
	// identity derived from a proto path changes when the path does -- and then
	// every policy that keys on it silently stops matching a renamed package.
	// Uniqueness is therefore not free: it needs a lint rule, which arrives with
	// the linter.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The tools this agent may call, and the only thing currently enforced.
	//
	// A MESSAGE rather than a repeated string, so this grows without a breaking
	// change. A guard, a per-tool ceiling, a rate -- each can arrive as a field on
	// ToolRef when its enforcer does. `repeated string` would have forced a
	// parallel field or a reshape the first time one did.
	//
	// The allowlist is the ONLY authority on what this agent may call. Nothing
	// widens it -- not a prompt, not a graph, not a runtime decision. When
	// something that orders calls arrives, it will be able to order only what is
	// already here.
	Tools         []*ToolRef `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetTools() []*ToolRef {
	if x != nil {
		return x.Tools
	}
	return nil
}

// One entry in an agent's allowlist.
//
// It carries a name and nothing else, on purpose: this message exists so that
// the NEXT thing an allowlist entry needs has somewhere to go, not so that
// fields can be declared ahead of the code that honours them.
type ToolRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool, as `<proto package>.<tool name>` -- `payments.v1.initiate_payment`.
	//
	// A different shape from Agent.name above, deliberately. An agent's name is a
	// deployment identity a human writes into policy; a tool's is a contract
	// address resolved against a catalogue. Two kinds of thing, two forms, said
	// out loud here so nobody has to infer it from examples.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRef) Reset() {
	*x = ToolRef{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRef) ProtoMessage() {}

func (x *ToolRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRef.ProtoReflect.Descriptor instead.
func (*ToolRef) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ToolRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_garm_agent_v1_agent_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Agent)(nil),
		Field:         50101,
		Name:          "garm.agent.v1.agent",
		Tag:           "bytes,50101,opt,name=agent",
		Filename:      "garm/agent/v1/agent.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional garm.agent.v1.Agent agent = 50101;
	E_Agent = &file_garm_agent_v1_agent_proto_extTypes[0]
)

var File_garm_agent_v1_agent_proto protoreflect.FileDescriptor

const file_garm_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x19garm/agent/v1/agent.proto\x12\rgarm.agent.v1\x1a google/protobuf/descriptor.proto\"I\n" +
	"\x05Agent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05tools\x18\x02 \x03(\v2\x16.garm.agent.v1.ToolRefR\x05tools\"\x1d\n" +
	"\aToolRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:M\n" +
	"\x05agent\x12\x1f.google.protobuf.ServiceOptions\x18\xb5\x87\x03 \x01(\v2\x14.garm.agent.v1.AgentR\x05agentB2Z0github.com/garm-ai/garm-ai/garm/agent/v1;agentv1b\x06proto3"

var (
	file_garm_agent_v1_agent_proto_rawDescOnce sync.Once
	file_garm_agent_v1_agent_proto_rawDescData []byte
)

func file_garm_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_garm_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_garm_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_agent_v1_agent_proto_rawDesc), len(file_garm_agent_v1_agent_proto_rawDesc)))
	})
	return file_garm_agent_v1_agent_proto_rawDescData
}

var file_garm_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_garm_agent_v1_agent_proto_goTypes = []any{
	(*Agent)(nil),                       // 0: garm.agent.v1.Agent
	(*ToolRef)(nil),                     // 1: garm.agent.v1.ToolRef
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_garm_agent_v1_agent_proto_depIdxs = []int32{
	1, // 0: garm.agent.v1.Agent.tools:type_name -> garm.agent.v1.ToolRef
	2, // 1: garm.agent.v1.agent:extendee -> google.protobuf.ServiceOptions
	0, // 2: garm.agent.v1.agent:type_name -> garm.agent.v1.Agent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_garm_agent_v1_agent_proto_init() }
func file_garm_agent_v1_agent_proto_init() {
	if File_garm_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_agent_v1_agent_proto_rawDesc), len(file_garm_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_garm_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_garm_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_garm_agent_v1_agent_proto_msgTypes,
		ExtensionInfos:    file_garm_agent_v1_agent_proto_extTypes,
	}.Build()
	File_garm_agent_v1_agent_proto = out.File
	file_garm_agent_v1_agent_proto_goTypes = nil
	file_garm_agent_v1_agent_proto_depIdxs = nil
}
