// An agent: a tool rund runs, asking a decider what to do next.
//
// IN A SEPARATE FILE FROM THE TOOLS IT CALLS, and NOTE THAT IT DOES NOT IMPORT
// THEM -- it cannot. An allowlist cites tools by NAME, so it creates no
// proto-level dependency, and buf correctly rejects the import as unused.
//
// That is the whole reason a resolver has a job: **the relationship between an
// agent and the tools it may call is one the proto system cannot express.**
// Nothing in protobuf will tell you a name resolves to nothing. So something
// else has to, which is `declared`.
//
// It is also why a partial tree is a real hazard rather than a contrived one.
// The previous estate shipped exactly this bug: a `--proto` flag compiled one
// directory and then ran the full rule set over it, so an agent naming an
// adopted tool was refused for naming a tool it could not see -- a valid tree
// reported broken, with no proto error to explain it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: testdata/v1/agent.proto

package testdatav1

import (
	_ "github.com/garm-ai/garm-ai/garm/tool/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_testdata_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_testdata_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

// Named InvokeResponse rather than RunRef purely to satisfy buf's
// RPC_RESPONSE_STANDARD_NAME. That is the SECOND naming rule STANDARD has fought
// in two steps, and the pattern is worth recording before real protos arrive:
//
//   - SERVICE_SUFFIX wants `SupportAssistantService`, where an agent is a named
//     actor and reads better without the suffix.
//   - RPC_RESPONSE_STANDARD_NAME wants InvokeResponse, where every agent's Invoke
//     returning one shared `RunRef` is good design -- and
//     RPC_REQUEST_RESPONSE_UNIQUE would then object to the sharing too.
//
// The previous estate hit all three, configured STANDARD anyway, and never ran
// it clean. The decision is NOT dodged, it is deferred to the step that writes a
// real proto -- and until then the fixture bends, not the ruleset.
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_testdata_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_testdata_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_testdata_v1_agent_proto protoreflect.FileDescriptor

const file_testdata_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x17testdata/v1/agent.proto\x12\vtestdata.v1\x1a\x17garm/tool/v1/tool.proto\")\n" +
	"\rInvokeRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"'\n" +
	"\x0eInvokeResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId2\xb6\x01\n" +
	"\x17SupportAssistantService\x12\x9a\x01\n" +
	"\x06Invoke\x12\x1a.testdata.v1.InvokeRequest\x1a\x1b.testdata.v1.InvokeResponse\"W\x92\xb5\x18S\n" +
	"\x11support-assistant\x12>\n" +
	"\x1a\n" +
	"\x18accounts.v1.get_customer\n" +
	" \n" +
	"\x1epayments.v1.get_payment_statusB3Z1github.com/garm-ai/garm-ai/testdata/v1;testdatav1b\x06proto3"

var (
	file_testdata_v1_agent_proto_rawDescOnce sync.Once
	file_testdata_v1_agent_proto_rawDescData []byte
)

func file_testdata_v1_agent_proto_rawDescGZIP() []byte {
	file_testdata_v1_agent_proto_rawDescOnce.Do(func() {
		file_testdata_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_v1_agent_proto_rawDesc), len(file_testdata_v1_agent_proto_rawDesc)))
	})
	return file_testdata_v1_agent_proto_rawDescData
}

var file_testdata_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testdata_v1_agent_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: testdata.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: testdata.v1.InvokeResponse
}
var file_testdata_v1_agent_proto_depIdxs = []int32{
	0, // 0: testdata.v1.SupportAssistantService.Invoke:input_type -> testdata.v1.InvokeRequest
	1, // 1: testdata.v1.SupportAssistantService.Invoke:output_type -> testdata.v1.InvokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_v1_agent_proto_init() }
func file_testdata_v1_agent_proto_init() {
	if File_testdata_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_v1_agent_proto_rawDesc), len(file_testdata_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_v1_agent_proto_goTypes,
		DependencyIndexes: file_testdata_v1_agent_proto_depIdxs,
		MessageInfos:      file_testdata_v1_agent_proto_msgTypes,
	}.Build()
	File_testdata_v1_agent_proto = out.File
	file_testdata_v1_agent_proto_goTypes = nil
	file_testdata_v1_agent_proto_depIdxs = nil
}
