// A service that declares the agent option, so a test can read it back off a
// real compiled descriptor rather than off a struct the test filled in itself.
//
// That distinction is not pedantry. In the estate this replaces, four separate
// tests passed while the behaviour they covered was broken, and every one failed
// the same way: the fixture was built by hand, so it could not express the thing
// that was wrong. A test that fabricates its own input proves the test compiles.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: testdata/v1/testdata.proto

package testdatav1

import (
	_ "github.com/garm-ai/garm-ai/garm/agent/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_testdata_v1_testdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_testdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_testdata_v1_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_testdata_v1_testdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_testdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_testdata_v1_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_testdata_v1_testdata_proto protoreflect.FileDescriptor

const file_testdata_v1_testdata_proto_rawDesc = "" +
	"\n" +
	"\x1atestdata/v1/testdata.proto\x12\vtestdata.v1\x1a\x19garm/agent/v1/agent.proto\")\n" +
	"\rInvokeRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"&\n" +
	"\x0eInvokeResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2\xb3\x01\n" +
	"\x17SupportAssistantService\x12A\n" +
	"\x06Invoke\x12\x1a.testdata.v1.InvokeRequest\x1a\x1b.testdata.v1.InvokeResponse\x1aU\xaa\xbb\x18Q\n" +
	"\x11support-assistant\x12\x1a\n" +
	"\x18accounts.v1.get_customer\x12 \n" +
	"\x1epayments.v1.get_payment_statusB3Z1github.com/garm-ai/garm-ai/testdata/v1;testdatav1b\x06proto3"

var (
	file_testdata_v1_testdata_proto_rawDescOnce sync.Once
	file_testdata_v1_testdata_proto_rawDescData []byte
)

func file_testdata_v1_testdata_proto_rawDescGZIP() []byte {
	file_testdata_v1_testdata_proto_rawDescOnce.Do(func() {
		file_testdata_v1_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_v1_testdata_proto_rawDesc), len(file_testdata_v1_testdata_proto_rawDesc)))
	})
	return file_testdata_v1_testdata_proto_rawDescData
}

var file_testdata_v1_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testdata_v1_testdata_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: testdata.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: testdata.v1.InvokeResponse
}
var file_testdata_v1_testdata_proto_depIdxs = []int32{
	0, // 0: testdata.v1.SupportAssistantService.Invoke:input_type -> testdata.v1.InvokeRequest
	1, // 1: testdata.v1.SupportAssistantService.Invoke:output_type -> testdata.v1.InvokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_v1_testdata_proto_init() }
func file_testdata_v1_testdata_proto_init() {
	if File_testdata_v1_testdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_v1_testdata_proto_rawDesc), len(file_testdata_v1_testdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_v1_testdata_proto_goTypes,
		DependencyIndexes: file_testdata_v1_testdata_proto_depIdxs,
		MessageInfos:      file_testdata_v1_testdata_proto_msgTypes,
	}.Build()
	File_testdata_v1_testdata_proto = out.File
	file_testdata_v1_testdata_proto_goTypes = nil
	file_testdata_v1_testdata_proto_depIdxs = nil
}
