// Code generated by protoc-gen-garm-go. DO NOT EDIT.
// source: testdata/v1/tools.proto
//
// Each Handler interface below has NO Unimplemented embed, and that is the
// feature. Add a tool to the .proto, forget to implement it, and the build FAILS
// TO COMPILE -- rather than mounting and answering Unimplemented to a real
// caller at run time. The embed grpc-go emits buys source compatibility and
// pays for it with half-implemented services that start cleanly.
//
// A tool whose option carries `agent` appears nowhere here: a runner answers it,
// so a handler method would be one nobody may implement.

package testdatav1

import (
	context "context"
	fmt "fmt"
	serve "github.com/garm-ai/garm-ai/serve"
	proto "google.golang.org/protobuf/proto"
)

// AccountsServiceHandler implements every tool AccountsService declares, in plain proto
// signatures with no transport wrapper.
type AccountsServiceHandler interface {
	// GetCustomer answers the tool "accounts.v1.get_customer".
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
}

// AccountsServiceTools is every tool NAME AccountsService answers, in
// declaration order: identities, never addresses.
var AccountsServiceTools = []string{
	"accounts.v1.get_customer",
}

// ServeAccountsService mounts every tool AccountsService declares on r. It
// returns on the first failure, having mounted the tools before it, so a
// transport should not announce itself until this has returned nil.
func ServeAccountsService(r serve.Registrar, h AccountsServiceHandler) error {
	if err := r.Endpoint(
		"accounts.v1.get_customer",
		"testdata.v1.AccountsService.GetCustomer",
		func() proto.Message { return new(GetCustomerRequest) },
		func(ctx context.Context, m proto.Message) (proto.Message, error) {
			in, ok := m.(*GetCustomerRequest)
			if !ok {
				return nil, fmt.Errorf("accounts.v1.get_customer: request is %T, want %T", m, (*GetCustomerRequest)(nil))
			}
			out, err := h.GetCustomer(ctx, in)
			if err != nil {
				return nil, err
			}
			if out == nil {
				return nil, fmt.Errorf("accounts.v1.get_customer: handler returned no response and no error")
			}
			return out, nil
		},
	); err != nil {
		return err
	}
	return nil
}

// PaymentsServiceHandler implements every tool PaymentsService declares, in plain proto
// signatures with no transport wrapper.
type PaymentsServiceHandler interface {
	// GetPaymentStatus answers the tool "payments.v1.get_payment_status".
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentStatusResponse, error)
}

// PaymentsServiceTools is every tool NAME PaymentsService answers, in
// declaration order: identities, never addresses.
var PaymentsServiceTools = []string{
	"payments.v1.get_payment_status",
}

// ServePaymentsService mounts every tool PaymentsService declares on r. It
// returns on the first failure, having mounted the tools before it, so a
// transport should not announce itself until this has returned nil.
func ServePaymentsService(r serve.Registrar, h PaymentsServiceHandler) error {
	if err := r.Endpoint(
		"payments.v1.get_payment_status",
		"testdata.v1.PaymentsService.GetPaymentStatus",
		func() proto.Message { return new(GetPaymentStatusRequest) },
		func(ctx context.Context, m proto.Message) (proto.Message, error) {
			in, ok := m.(*GetPaymentStatusRequest)
			if !ok {
				return nil, fmt.Errorf("payments.v1.get_payment_status: request is %T, want %T", m, (*GetPaymentStatusRequest)(nil))
			}
			out, err := h.GetPaymentStatus(ctx, in)
			if err != nil {
				return nil, err
			}
			if out == nil {
				return nil, fmt.Errorf("payments.v1.get_payment_status: handler returned no response and no error")
			}
			return out, nil
		},
	); err != nil {
		return err
	}
	return nil
}
