// Plain tools: a service answers each call itself.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: testdata/v1/tools.proto

package testdatav1

import (
	_ "github.com/garm-ai/garm-ai/garm/tool/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_testdata_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_testdata_v1_tools_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_testdata_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_testdata_v1_tools_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_testdata_v1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_testdata_v1_tools_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_testdata_v1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_v1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_testdata_v1_tools_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_testdata_v1_tools_proto protoreflect.FileDescriptor

const file_testdata_v1_tools_proto_rawDesc = "" +
	"\n" +
	"\x17testdata/v1/tools.proto\x12\vtestdata.v1\x1a\x17garm/tool/v1/tool.proto\"5\n" +
	"\x12GetCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"8\n" +
	"\x13GetCustomerResponse\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"8\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"2\n" +
	"\x18GetPaymentStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x89\x01\n" +
	"\x0fAccountsService\x12v\n" +
	"\vGetCustomer\x12\x1f.testdata.v1.GetCustomerRequest\x1a .testdata.v1.GetCustomerResponse\"$\x92\xb5\x18 \n" +
	"\x18accounts.v1.get_customer\x1a\x04\n" +
	"\x02\b\x022\x9f\x01\n" +
	"\x0fPaymentsService\x12\x8b\x01\n" +
	"\x10GetPaymentStatus\x12$.testdata.v1.GetPaymentStatusRequest\x1a%.testdata.v1.GetPaymentStatusResponse\"*\x92\xb5\x18&\n" +
	"\x1epayments.v1.get_payment_status\x1a\x04\n" +
	"\x02\b\x05B3Z1github.com/garm-ai/garm-ai/testdata/v1;testdatav1b\x06proto3"

var (
	file_testdata_v1_tools_proto_rawDescOnce sync.Once
	file_testdata_v1_tools_proto_rawDescData []byte
)

func file_testdata_v1_tools_proto_rawDescGZIP() []byte {
	file_testdata_v1_tools_proto_rawDescOnce.Do(func() {
		file_testdata_v1_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_v1_tools_proto_rawDesc), len(file_testdata_v1_tools_proto_rawDesc)))
	})
	return file_testdata_v1_tools_proto_rawDescData
}

var file_testdata_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testdata_v1_tools_proto_goTypes = []any{
	(*GetCustomerRequest)(nil),       // 0: testdata.v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),      // 1: testdata.v1.GetCustomerResponse
	(*GetPaymentStatusRequest)(nil),  // 2: testdata.v1.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil), // 3: testdata.v1.GetPaymentStatusResponse
}
var file_testdata_v1_tools_proto_depIdxs = []int32{
	0, // 0: testdata.v1.AccountsService.GetCustomer:input_type -> testdata.v1.GetCustomerRequest
	2, // 1: testdata.v1.PaymentsService.GetPaymentStatus:input_type -> testdata.v1.GetPaymentStatusRequest
	1, // 2: testdata.v1.AccountsService.GetCustomer:output_type -> testdata.v1.GetCustomerResponse
	3, // 3: testdata.v1.PaymentsService.GetPaymentStatus:output_type -> testdata.v1.GetPaymentStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_v1_tools_proto_init() }
func file_testdata_v1_tools_proto_init() {
	if File_testdata_v1_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_v1_tools_proto_rawDesc), len(file_testdata_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_testdata_v1_tools_proto_goTypes,
		DependencyIndexes: file_testdata_v1_tools_proto_depIdxs,
		MessageInfos:      file_testdata_v1_tools_proto_msgTypes,
	}.Build()
	File_testdata_v1_tools_proto = out.File
	file_testdata_v1_tools_proto_goTypes = nil
	file_testdata_v1_tools_proto_depIdxs = nil
}
