// Code generated by protoc-gen-garm-go. DO NOT EDIT.
// source: testdata/v1/tools.proto
//
// Each Handler interface below has NO Unimplemented embed, and that is the
// feature. Add a tool to the .proto, forget to implement it, and the build FAILS
// TO COMPILE -- rather than mounting and answering Unimplemented to a real
// caller at run time. The embed grpc-go emits buys source compatibility and
// pays for it with half-implemented services that start cleanly.
//
// A tool whose option carries `agent` appears nowhere here: rund runs it with a decider,
// so a handler method would be one nobody may implement.

package testdatav1

import (
	context "context"
	fmt "fmt"
	call "github.com/garm-ai/garm-ai/call"
	serve "github.com/garm-ai/garm-ai/serve"
	proto "google.golang.org/protobuf/proto"
	time "time"
)

// AccountsServiceHandler implements every tool AccountsService declares, in plain proto
// signatures with no transport wrapper.
type AccountsServiceHandler interface {
	// GetCustomer answers the tool "accounts.v1.get_customer".
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
}

// AccountsServiceTools is every tool NAME AccountsService answers, in
// declaration order: identities, never addresses.
var AccountsServiceTools = []string{
	"accounts.v1.get_customer",
}

// ServeAccountsService mounts every tool AccountsService declares on r. It
// returns on the first failure, having mounted the tools before it, so a
// transport should not announce itself until this has returned nil.
func ServeAccountsService(r serve.Registrar, h AccountsServiceHandler) error {
	if err := r.Endpoint(
		"accounts.v1.get_customer",
		"testdata.v1.AccountsService.GetCustomer",
		2*time.Second,
		func() proto.Message { return new(GetCustomerRequest) },
		func(ctx context.Context, m proto.Message) (proto.Message, error) {
			in, ok := m.(*GetCustomerRequest)
			if !ok {
				return nil, fmt.Errorf("accounts.v1.get_customer: request is %T, want %T", m, (*GetCustomerRequest)(nil))
			}
			out, err := h.GetCustomer(ctx, in)
			if err != nil {
				return nil, err
			}
			if out == nil {
				return nil, fmt.Errorf("accounts.v1.get_customer: handler returned no response and no error")
			}
			return out, nil
		},
	); err != nil {
		return err
	}
	return nil
}

// AccountsServiceClient calls the tools AccountsService declares, by NAME.
//
// It knows no subject and no broker: it holds a call.Invoker, and which
// transport that is remains the process's business.
type AccountsServiceClient struct{ Invoker call.Invoker }

// NewAccountsServiceClient builds a client over any transport.
func NewAccountsServiceClient(i call.Invoker) AccountsServiceClient {
	return AccountsServiceClient{Invoker: i}
}

// GetCustomer calls the tool "accounts.v1.get_customer".
//
// The deadline is 2s -- the budget this tool DECLARED --
// plus the hops. No caller invents a number. A shorter deadline already on
// ctx still wins, because a caller's own patience is its own business.
//
// Only the first Options is used.
func (c AccountsServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...call.Options) (*GetCustomerResponse, error) {
	body, err := proto.Marshal(in)
	if err != nil {
		return nil, fmt.Errorf("accounts.v1.get_customer: marshalling the request: %w", err)
	}
	var o call.Options
	if len(opts) > 0 {
		o = opts[0]
	}
	ctx, cancel := context.WithTimeout(ctx, call.Deadline(2*time.Second))
	defer cancel()
	raw, err := c.Invoker.Invoke(ctx, "accounts.v1.get_customer", body, o)
	if err != nil {
		return nil, err
	}
	var resp GetCustomerResponse
	if err := proto.Unmarshal(raw, &resp); err != nil {
		return nil, fmt.Errorf("accounts.v1.get_customer: the answer is not a %T: %w", &resp, err)
	}
	return &resp, nil
}

// PaymentsServiceHandler implements every tool PaymentsService declares, in plain proto
// signatures with no transport wrapper.
type PaymentsServiceHandler interface {
	// GetPaymentStatus answers the tool "payments.v1.get_payment_status".
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentStatusResponse, error)
}

// PaymentsServiceTools is every tool NAME PaymentsService answers, in
// declaration order: identities, never addresses.
var PaymentsServiceTools = []string{
	"payments.v1.get_payment_status",
}

// ServePaymentsService mounts every tool PaymentsService declares on r. It
// returns on the first failure, having mounted the tools before it, so a
// transport should not announce itself until this has returned nil.
func ServePaymentsService(r serve.Registrar, h PaymentsServiceHandler) error {
	if err := r.Endpoint(
		"payments.v1.get_payment_status",
		"testdata.v1.PaymentsService.GetPaymentStatus",
		5*time.Second,
		func() proto.Message { return new(GetPaymentStatusRequest) },
		func(ctx context.Context, m proto.Message) (proto.Message, error) {
			in, ok := m.(*GetPaymentStatusRequest)
			if !ok {
				return nil, fmt.Errorf("payments.v1.get_payment_status: request is %T, want %T", m, (*GetPaymentStatusRequest)(nil))
			}
			out, err := h.GetPaymentStatus(ctx, in)
			if err != nil {
				return nil, err
			}
			if out == nil {
				return nil, fmt.Errorf("payments.v1.get_payment_status: handler returned no response and no error")
			}
			return out, nil
		},
	); err != nil {
		return err
	}
	return nil
}

// PaymentsServiceClient calls the tools PaymentsService declares, by NAME.
//
// It knows no subject and no broker: it holds a call.Invoker, and which
// transport that is remains the process's business.
type PaymentsServiceClient struct{ Invoker call.Invoker }

// NewPaymentsServiceClient builds a client over any transport.
func NewPaymentsServiceClient(i call.Invoker) PaymentsServiceClient {
	return PaymentsServiceClient{Invoker: i}
}

// GetPaymentStatus calls the tool "payments.v1.get_payment_status".
//
// The deadline is 5s -- the budget this tool DECLARED --
// plus the hops. No caller invents a number. A shorter deadline already on
// ctx still wins, because a caller's own patience is its own business.
//
// Only the first Options is used.
func (c PaymentsServiceClient) GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...call.Options) (*GetPaymentStatusResponse, error) {
	body, err := proto.Marshal(in)
	if err != nil {
		return nil, fmt.Errorf("payments.v1.get_payment_status: marshalling the request: %w", err)
	}
	var o call.Options
	if len(opts) > 0 {
		o = opts[0]
	}
	ctx, cancel := context.WithTimeout(ctx, call.Deadline(5*time.Second))
	defer cancel()
	raw, err := c.Invoker.Invoke(ctx, "payments.v1.get_payment_status", body, o)
	if err != nil {
		return nil, err
	}
	var resp GetPaymentStatusResponse
	if err := proto.Unmarshal(raw, &resp); err != nil {
		return nil, fmt.Errorf("payments.v1.get_payment_status: the answer is not a %T: %w", &resp, err)
	}
	return &resp, nil
}
