// The platform's own front door.
//
// DELIBERATELY NOT A SET OF TOOLS, and the reason is recursion: invoking a tool
// goes THROUGH this, so if `invoke` were itself a tool then invoking it would
// create a run that invoked it. "Everything is a tool" governs what the platform
// serves on behalf of others, not the door you come in by.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/run/v1/run.proto

package runv1

import (
	v1 "github.com/garm-ai/garm-ai/garm/invoke/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED RunState = 0
	// The run happened and nothing was kept. The honest answer for a synchronous
	// call in a build with no store: NOT a lie that it never existed, and not a
	// fabricated result.
	RunState_RUN_STATE_NOT_RETAINED RunState = 1
	// Durable and not yet finished: queued for a replica, or executing. One
	// state for both, because the caller's question is "is there an answer yet".
	RunState_RUN_STATE_RUNNING   RunState = 2
	RunState_RUN_STATE_SUCCEEDED RunState = 3
	RunState_RUN_STATE_FAILED    RunState = 4
	// Cancelled by an operator (the store's own command) before it finished.
	RunState_RUN_STATE_CANCELLED RunState = 5
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_NOT_RETAINED",
		2: "RUN_STATE_RUNNING",
		3: "RUN_STATE_SUCCEEDED",
		4: "RUN_STATE_FAILED",
		5: "RUN_STATE_CANCELLED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED":  0,
		"RUN_STATE_NOT_RETAINED": 1,
		"RUN_STATE_RUNNING":      2,
		"RUN_STATE_SUCCEEDED":    3,
		"RUN_STATE_FAILED":       4,
		"RUN_STATE_CANCELLED":    5,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_run_v1_run_proto_enumTypes[0].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_garm_run_v1_run_proto_enumTypes[0]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{0}
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool's declared NAME. Identity, never an address: a caller asks for
	// `payments.v1.get_balance` and never for a proto path.
	Tool string `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	// The tool's request message, marshalled.
	//
	// `bytes`, NOT google.protobuf.Any. An Any carries a type URL, which is a
	// SECOND statement of a type the tool name already determines -- two sources
	// that can disagree, about the one thing this platform refuses to state twice.
	// rund holds the catalogue, so it can decode this for a log line without the
	// wire carrying a redundant claim.
	//
	// THIS IS THE ONLY FIELD A MODEL'S OUTPUT EVER REACHES. Everything that governs
	// a call -- the ids, the budget, an idempotency key -- travels in NATS HEADERS,
	// which the caller's runtime sets and a model cannot. That is structural rather
	// than a rule somebody has to remember: a model produces arguments, and
	// arguments are in here.
	Input         []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_garm_run_v1_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *InvokeRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always set. Every call has a run, whether or not anything is stored under it.
	//
	// Distinct from the correlation id: a correlation spans one caller's flow,
	// which may start several runs.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// The second arm joined when the run store did, additively -- which is why
	// the oneof was there with one arm from the start.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*InvokeResponse_Result
	//	*InvokeResponse_Pending
	Outcome       isInvokeResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_garm_run_v1_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *InvokeResponse) GetOutcome() isInvokeResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*InvokeResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *InvokeResponse) GetPending() *Pending {
	if x != nil {
		if x, ok := x.Outcome.(*InvokeResponse_Pending); ok {
			return x.Pending
		}
	}
	return nil
}

type isInvokeResponse_Outcome interface {
	isInvokeResponse_Outcome()
}

type InvokeResponse_Result struct {
	// The tool answered within its declared budget. Only possible for a tool
	// whose delivery is Sync.
	Result []byte `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type InvokeResponse_Pending struct {
	// The run is durable and will execute without the caller. Only possible
	// for a tool whose delivery is Async, and only when the caller supplied an
	// idempotency key: that key is the run id, so a retry of Invoke is the same
	// run and never a second one.
	Pending *Pending `protobuf:"bytes,3,opt,name=pending,proto3,oneof"`
}

func (*InvokeResponse_Result) isInvokeResponse_Outcome() {}

func (*InvokeResponse_Pending) isInvokeResponse_Outcome() {}

// Pending carries nothing today. A message rather than a bool so that what a
// pending run can say about itself (a queue position, an estimate) is additive.
type Pending struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pending) Reset() {
	*x = Pending{}
	mi := &file_garm_run_v1_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pending) ProtoMessage() {}

func (x *Pending) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pending.ProtoReflect.Descriptor instead.
func (*Pending) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{2}
}

type FetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// How long rund may hold the request before answering, when the run is still
	// RUNNING. Zero answers at once. rund caps this (30s): a request must never
	// outlive the bus's own timeouts. A blocking Fetch is how a caller waits for
	// an answer without polling -- one request in flight, not one per second.
	Wait          *durationpb.Duration `protobuf:"bytes,2,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_garm_run_v1_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{3}
}

func (x *FetchRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *FetchRequest) GetWait() *durationpb.Duration {
	if x != nil {
		return x.Wait
	}
	return nil
}

type FetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State RunState               `protobuf:"varint,1,opt,name=state,proto3,enum=garm.run.v1.RunState" json:"state,omitempty"`
	// Set when the run reached a terminal state. A FAILED run's error is the
	// tool's own, with its kind, as a sync caller would have received it.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*FetchResponse_Result
	//	*FetchResponse_Error
	Outcome isFetchResponse_Outcome `protobuf_oneof:"outcome"`
	// Where the run is, in the run's own words: `queued`, `calling:<i>`, `done`.
	// A word and a reference, never a payload. Empty for a run that has no store.
	Stage       string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// The tool the run invoked, so a caller holding only a run id can decode the
	// result against the catalogue.
	Tool          string `protobuf:"bytes,7,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_garm_run_v1_run_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{4}
}

func (x *FetchResponse) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *FetchResponse) GetOutcome() isFetchResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *FetchResponse) GetResult() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*FetchResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *FetchResponse) GetError() *v1.Error {
	if x != nil {
		if x, ok := x.Outcome.(*FetchResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *FetchResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *FetchResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FetchResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *FetchResponse) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

type isFetchResponse_Outcome interface {
	isFetchResponse_Outcome()
}

type FetchResponse_Result struct {
	Result []byte `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type FetchResponse_Error struct {
	Error *v1.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*FetchResponse_Result) isFetchResponse_Outcome() {}

func (*FetchResponse_Error) isFetchResponse_Outcome() {}

type EventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Return events with seq > after. 0 is the start.
	After uint64 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	// How long rund may hold the request when no event is past the cursor yet.
	// Zero answers at once. Capped at 30s, as Fetch's wait is.
	Wait          *durationpb.Duration `protobuf:"bytes,3,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_garm_run_v1_run_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{5}
}

func (x *EventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EventsRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *EventsRequest) GetWait() *durationpb.Duration {
	if x != nil {
		return x.Wait
	}
	return nil
}

type EventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// In sequence order, at most 256; a caller a long way behind pages.
	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// True once the run's stream is closed and every event is at or before this
	// reply: there will be no more.
	Closed        bool `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_garm_run_v1_run_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{6}
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventsResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

// One thing that happened in a run. A WORD AND A REFERENCE, NEVER A PAYLOAD --
// with one bounded exception, chunk, whose text is capped at 4 KB. done carries
// no result: a result can be large, is already in the run, and is fetched with
// the ownership check and the typed decoding Fetch has.
//
// The same bytes are what the run writes to its durable stream and what rund
// publishes live on garm.run.v1.<OWNER>.out.<run_id>.<seq>, so a late
// subscriber's catch-up and the live feed are the same thing from two places.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// The stream position, from 1, assigned once at write. What a cursor names,
	// and what lets a subscriber stitch catch-up to live without a duplicate.
	Seq uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	At  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_Stage
	//	*Event_Step
	//	*Event_Progress
	//	*Event_Question
	//	*Event_Chunk
	//	*Event_Done
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_garm_run_v1_run_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetStage() *Stage {
	if x != nil {
		if x, ok := x.Kind.(*Event_Stage); ok {
			return x.Stage
		}
	}
	return nil
}

func (x *Event) GetStep() *Step {
	if x != nil {
		if x, ok := x.Kind.(*Event_Step); ok {
			return x.Step
		}
	}
	return nil
}

func (x *Event) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Kind.(*Event_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *Event) GetQuestion() *Question {
	if x != nil {
		if x, ok := x.Kind.(*Event_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *Event) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Kind.(*Event_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *Event) GetDone() *Done {
	if x != nil {
		if x, ok := x.Kind.(*Event_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Stage struct {
	Stage *Stage `protobuf:"bytes,10,opt,name=stage,proto3,oneof"` // the stage word, as Fetch shows it: calling:<i>, done
}

type Event_Step struct {
	Step *Step `protobuf:"bytes,11,opt,name=step,proto3,oneof"` // a tool-call step's key and outcome kind; no bytes
}

type Event_Progress struct {
	Progress *Progress `protobuf:"bytes,12,opt,name=progress,proto3,oneof"` // a decider's short text and optional fraction
}

type Event_Question struct {
	Question *Question `protobuf:"bytes,13,opt,name=question,proto3,oneof"` // a question's id and text, for a decider that needs input
}

type Event_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,14,opt,name=chunk,proto3,oneof"` // a piece of a streamed answer, in order, at most 4 KB of text
}

type Event_Done struct {
	Done *Done `protobuf:"bytes,15,opt,name=done,proto3,oneof"` // the terminal state; the result is fetched, not pushed
}

func (*Event_Stage) isEvent_Kind() {}

func (*Event_Step) isEvent_Kind() {}

func (*Event_Progress) isEvent_Kind() {}

func (*Event_Question) isEvent_Kind() {}

func (*Event_Chunk) isEvent_Kind() {}

func (*Event_Done) isEvent_Kind() {}

type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_garm_run_v1_run_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{8}
}

func (x *Stage) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // the step's idempotency key, <run_id>:<i>
	// The step's outcome: UNSPECIFIED means it succeeded; otherwise the tool's
	// own kind, as a sync caller would have received it.
	Kind          v1.ErrorKind `protobuf:"varint,2,opt,name=kind,proto3,enum=garm.invoke.v1.ErrorKind" json:"kind,omitempty"`
	Tool          string       `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_garm_run_v1_run_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{9}
}

func (x *Step) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Step) GetKind() v1.ErrorKind {
	if x != nil {
		return x.Kind
	}
	return v1.ErrorKind(0)
}

func (x *Step) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Fraction      *float32               `protobuf:"fixed32,2,opt,name=fraction,proto3,oneof" json:"fraction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_garm_run_v1_run_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{10}
}

func (x *Progress) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Progress) GetFraction() float32 {
	if x != nil && x.Fraction != nil {
		return *x.Fraction
	}
	return 0
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_garm_run_v1_run_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{11}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// At most 4 KB; a write over it is refused. Larger content is an artefact
	// reference in a Progress or Question, never bytes on the bus.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_garm_run_v1_run_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{12}
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RunState               `protobuf:"varint,1,opt,name=state,proto3,enum=garm.run.v1.RunState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_garm_run_v1_run_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_garm_run_v1_run_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_garm_run_v1_run_proto_rawDescGZIP(), []int{13}
}

func (x *Done) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

var File_garm_run_v1_run_proto protoreflect.FileDescriptor

const file_garm_run_v1_run_proto_rawDesc = "" +
	"\n" +
	"\x15garm/run/v1/run.proto\x12\vgarm.run.v1\x1a\x1agarm/invoke/v1/error.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\rInvokeRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\"~\n" +
	"\x0eInvokeResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\x06result\x18\x02 \x01(\fH\x00R\x06result\x120\n" +
	"\apending\x18\x03 \x01(\v2\x14.garm.run.v1.PendingH\x00R\apendingB\t\n" +
	"\aoutcome\"\t\n" +
	"\aPending\"T\n" +
	"\fFetchRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12-\n" +
	"\x04wait\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x04wait\"\xb4\x02\n" +
	"\rFetchResponse\x12+\n" +
	"\x05state\x18\x01 \x01(\x0e2\x15.garm.run.v1.RunStateR\x05state\x12\x18\n" +
	"\x06result\x18\x02 \x01(\fH\x00R\x06result\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.garm.invoke.v1.ErrorH\x00R\x05error\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x12\n" +
	"\x04tool\x18\a \x01(\tR\x04toolB\t\n" +
	"\aoutcome\"k\n" +
	"\rEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\x12-\n" +
	"\x04wait\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x04wait\"T\n" +
	"\x0eEventsResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.garm.run.v1.EventR\x06events\x12\x16\n" +
	"\x06closed\x18\x02 \x01(\bR\x06closed\"\xf8\x02\n" +
	"\x05Event\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12*\n" +
	"\x05stage\x18\n" +
	" \x01(\v2\x12.garm.run.v1.StageH\x00R\x05stage\x12'\n" +
	"\x04step\x18\v \x01(\v2\x11.garm.run.v1.StepH\x00R\x04step\x123\n" +
	"\bprogress\x18\f \x01(\v2\x15.garm.run.v1.ProgressH\x00R\bprogress\x123\n" +
	"\bquestion\x18\r \x01(\v2\x15.garm.run.v1.QuestionH\x00R\bquestion\x12*\n" +
	"\x05chunk\x18\x0e \x01(\v2\x12.garm.run.v1.ChunkH\x00R\x05chunk\x12'\n" +
	"\x04done\x18\x0f \x01(\v2\x11.garm.run.v1.DoneH\x00R\x04doneB\x06\n" +
	"\x04kind\"\x1d\n" +
	"\x05Stage\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\"[\n" +
	"\x04Step\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x19.garm.invoke.v1.ErrorKindR\x04kind\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\"L\n" +
	"\bProgress\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\bfraction\x18\x02 \x01(\x02H\x00R\bfraction\x88\x01\x01B\v\n" +
	"\t_fraction\".\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"3\n" +
	"\x04Done\x12+\n" +
	"\x05state\x18\x01 \x01(\x0e2\x15.garm.run.v1.RunStateR\x05state*\xa0\x01\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RUN_STATE_NOT_RETAINED\x10\x01\x12\x15\n" +
	"\x11RUN_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13RUN_STATE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10RUN_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13RUN_STATE_CANCELLED\x10\x052\xd2\x01\n" +
	"\n" +
	"RunService\x12A\n" +
	"\x06Invoke\x12\x1a.garm.run.v1.InvokeRequest\x1a\x1b.garm.run.v1.InvokeResponse\x12>\n" +
	"\x05Fetch\x12\x19.garm.run.v1.FetchRequest\x1a\x1a.garm.run.v1.FetchResponse\x12A\n" +
	"\x06Events\x12\x1a.garm.run.v1.EventsRequest\x1a\x1b.garm.run.v1.EventsResponseB.Z,github.com/garm-ai/garm-ai/garm/run/v1;runv1b\x06proto3"

var (
	file_garm_run_v1_run_proto_rawDescOnce sync.Once
	file_garm_run_v1_run_proto_rawDescData []byte
)

func file_garm_run_v1_run_proto_rawDescGZIP() []byte {
	file_garm_run_v1_run_proto_rawDescOnce.Do(func() {
		file_garm_run_v1_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_run_v1_run_proto_rawDesc), len(file_garm_run_v1_run_proto_rawDesc)))
	})
	return file_garm_run_v1_run_proto_rawDescData
}

var file_garm_run_v1_run_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_garm_run_v1_run_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_garm_run_v1_run_proto_goTypes = []any{
	(RunState)(0),                 // 0: garm.run.v1.RunState
	(*InvokeRequest)(nil),         // 1: garm.run.v1.InvokeRequest
	(*InvokeResponse)(nil),        // 2: garm.run.v1.InvokeResponse
	(*Pending)(nil),               // 3: garm.run.v1.Pending
	(*FetchRequest)(nil),          // 4: garm.run.v1.FetchRequest
	(*FetchResponse)(nil),         // 5: garm.run.v1.FetchResponse
	(*EventsRequest)(nil),         // 6: garm.run.v1.EventsRequest
	(*EventsResponse)(nil),        // 7: garm.run.v1.EventsResponse
	(*Event)(nil),                 // 8: garm.run.v1.Event
	(*Stage)(nil),                 // 9: garm.run.v1.Stage
	(*Step)(nil),                  // 10: garm.run.v1.Step
	(*Progress)(nil),              // 11: garm.run.v1.Progress
	(*Question)(nil),              // 12: garm.run.v1.Question
	(*Chunk)(nil),                 // 13: garm.run.v1.Chunk
	(*Done)(nil),                  // 14: garm.run.v1.Done
	(*durationpb.Duration)(nil),   // 15: google.protobuf.Duration
	(*v1.Error)(nil),              // 16: garm.invoke.v1.Error
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(v1.ErrorKind)(0),             // 18: garm.invoke.v1.ErrorKind
}
var file_garm_run_v1_run_proto_depIdxs = []int32{
	3,  // 0: garm.run.v1.InvokeResponse.pending:type_name -> garm.run.v1.Pending
	15, // 1: garm.run.v1.FetchRequest.wait:type_name -> google.protobuf.Duration
	0,  // 2: garm.run.v1.FetchResponse.state:type_name -> garm.run.v1.RunState
	16, // 3: garm.run.v1.FetchResponse.error:type_name -> garm.invoke.v1.Error
	17, // 4: garm.run.v1.FetchResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 5: garm.run.v1.FetchResponse.completed_at:type_name -> google.protobuf.Timestamp
	15, // 6: garm.run.v1.EventsRequest.wait:type_name -> google.protobuf.Duration
	8,  // 7: garm.run.v1.EventsResponse.events:type_name -> garm.run.v1.Event
	17, // 8: garm.run.v1.Event.at:type_name -> google.protobuf.Timestamp
	9,  // 9: garm.run.v1.Event.stage:type_name -> garm.run.v1.Stage
	10, // 10: garm.run.v1.Event.step:type_name -> garm.run.v1.Step
	11, // 11: garm.run.v1.Event.progress:type_name -> garm.run.v1.Progress
	12, // 12: garm.run.v1.Event.question:type_name -> garm.run.v1.Question
	13, // 13: garm.run.v1.Event.chunk:type_name -> garm.run.v1.Chunk
	14, // 14: garm.run.v1.Event.done:type_name -> garm.run.v1.Done
	18, // 15: garm.run.v1.Step.kind:type_name -> garm.invoke.v1.ErrorKind
	0,  // 16: garm.run.v1.Done.state:type_name -> garm.run.v1.RunState
	1,  // 17: garm.run.v1.RunService.Invoke:input_type -> garm.run.v1.InvokeRequest
	4,  // 18: garm.run.v1.RunService.Fetch:input_type -> garm.run.v1.FetchRequest
	6,  // 19: garm.run.v1.RunService.Events:input_type -> garm.run.v1.EventsRequest
	2,  // 20: garm.run.v1.RunService.Invoke:output_type -> garm.run.v1.InvokeResponse
	5,  // 21: garm.run.v1.RunService.Fetch:output_type -> garm.run.v1.FetchResponse
	7,  // 22: garm.run.v1.RunService.Events:output_type -> garm.run.v1.EventsResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_garm_run_v1_run_proto_init() }
func file_garm_run_v1_run_proto_init() {
	if File_garm_run_v1_run_proto != nil {
		return
	}
	file_garm_run_v1_run_proto_msgTypes[1].OneofWrappers = []any{
		(*InvokeResponse_Result)(nil),
		(*InvokeResponse_Pending)(nil),
	}
	file_garm_run_v1_run_proto_msgTypes[4].OneofWrappers = []any{
		(*FetchResponse_Result)(nil),
		(*FetchResponse_Error)(nil),
	}
	file_garm_run_v1_run_proto_msgTypes[7].OneofWrappers = []any{
		(*Event_Stage)(nil),
		(*Event_Step)(nil),
		(*Event_Progress)(nil),
		(*Event_Question)(nil),
		(*Event_Chunk)(nil),
		(*Event_Done)(nil),
	}
	file_garm_run_v1_run_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_run_v1_run_proto_rawDesc), len(file_garm_run_v1_run_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_garm_run_v1_run_proto_goTypes,
		DependencyIndexes: file_garm_run_v1_run_proto_depIdxs,
		EnumInfos:         file_garm_run_v1_run_proto_enumTypes,
		MessageInfos:      file_garm_run_v1_run_proto_msgTypes,
	}.Build()
	File_garm_run_v1_run_proto = out.File
	file_garm_run_v1_run_proto_goTypes = nil
	file_garm_run_v1_run_proto_depIdxs = nil
}
