// What a tool says when it cannot answer.
//
// A SEPARATE PACKAGE from garm.tool.v1 on purpose. That one is about DECLARATION:
// read at compose time, by a linter, to decide what exists. This is about
// INVOCATION: read at call time, by a transport, to decide what a caller is told.
// Different lifecycle, different readers, and folding them into one file would
// make every tool author's compile depend on the invocation surface evolving.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/invoke/v1/error.proto

package invokev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorKind is the closed set of reasons a call did not produce an answer.
//
// A member is admitted on one test: does a CALLER ACT DIFFERENTLY, or does a HUMAN
// DIAGNOSE DIFFERENTLY? Five pass. A sixth needs one of those to point at, or it
// is a taxonomy, and this platform has shipped a taxonomy nothing read before.
//
// Deliberately NOT HTTP status codes, which is what the estate this replaces used.
// "404" for a tool collapses two unrelated things -- the customer does not exist
// (the tool answering) and the tool does not exist (routing failing) -- and borrows
// a vocabulary from a protocol this platform does not speak.
type ErrorKind int32

const (
	// Never set deliberately. A transport treats it as INTERNAL, so an error that
	// reached the wire without a kind fails safe rather than silently.
	ErrorKind_ERROR_KIND_UNSPECIFIED ErrorKind = 0
	// The arguments will never be acceptable. Retrying unchanged cannot work.
	ErrorKind_ERROR_KIND_INVALID ErrorKind = 1
	// The thing asked about does not exist. The most common honest answer a tool
	// gives, and an ANSWER rather than a failure.
	ErrorKind_ERROR_KIND_NOT_FOUND ErrorKind = 2
	// The caller is not permitted -- by THIS TOOL's own rules, about its own data.
	// Platform authorisation refusing a call before a tool is reached is a different
	// event and does not appear here, because the tool never ran.
	ErrorKind_ERROR_KIND_DENIED ErrorKind = 3
	// Transient. The one kind where retrying with backoff is the right response.
	ErrorKind_ERROR_KIND_UNAVAILABLE ErrorKind = 4
	// The tool broke. Distinct from UNAVAILABLE because retrying probably will not
	// help, and distinct from the rest because the caller did nothing wrong.
	ErrorKind_ERROR_KIND_INTERNAL ErrorKind = 5
)

// Enum value maps for ErrorKind.
var (
	ErrorKind_name = map[int32]string{
		0: "ERROR_KIND_UNSPECIFIED",
		1: "ERROR_KIND_INVALID",
		2: "ERROR_KIND_NOT_FOUND",
		3: "ERROR_KIND_DENIED",
		4: "ERROR_KIND_UNAVAILABLE",
		5: "ERROR_KIND_INTERNAL",
	}
	ErrorKind_value = map[string]int32{
		"ERROR_KIND_UNSPECIFIED": 0,
		"ERROR_KIND_INVALID":     1,
		"ERROR_KIND_NOT_FOUND":   2,
		"ERROR_KIND_DENIED":      3,
		"ERROR_KIND_UNAVAILABLE": 4,
		"ERROR_KIND_INTERNAL":    5,
	}
)

func (x ErrorKind) Enum() *ErrorKind {
	p := new(ErrorKind)
	*p = x
	return p
}

func (x ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_invoke_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorKind) Type() protoreflect.EnumType {
	return &file_garm_invoke_v1_error_proto_enumTypes[0]
}

func (x ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorKind.Descriptor instead.
func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_garm_invoke_v1_error_proto_rawDescGZIP(), []int{0}
}

// Error is what crosses the wire. Every field here is safe for the caller to see.
//
// THERE IS NO CAUSE FIELD, and its absence is the design. A cause chain is exactly
// where the unsafe things live -- a connection string, a SQL fragment, a customer
// name inside a constraint violation -- so the chain stays in the answering
// service's own log, correlated by `id`. The caller learns what KIND of thing went
// wrong and a token to quote; it never learns how.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  ErrorKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=garm.invoke.v1.ErrorKind" json:"kind,omitempty"`
	// Published VERBATIM. Nothing automatic ever reaches it: a transport fills it
	// only from a message a tool author chose, and replaces it with a fixed string
	// for any error that did not name its kind.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Correlates to the cause chain in the answering service's log. A caller quotes
	// it; an operator joins on it.
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_garm_invoke_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_garm_invoke_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_garm_invoke_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetKind() ErrorKind {
	if x != nil {
		return x.Kind
	}
	return ErrorKind_ERROR_KIND_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_garm_invoke_v1_error_proto protoreflect.FileDescriptor

const file_garm_invoke_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1agarm/invoke/v1/error.proto\x12\x0egarm.invoke.v1\"`\n" +
	"\x05Error\x12-\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x19.garm.invoke.v1.ErrorKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id*\xa5\x01\n" +
	"\tErrorKind\x12\x1a\n" +
	"\x16ERROR_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ERROR_KIND_INVALID\x10\x01\x12\x18\n" +
	"\x14ERROR_KIND_NOT_FOUND\x10\x02\x12\x15\n" +
	"\x11ERROR_KIND_DENIED\x10\x03\x12\x1a\n" +
	"\x16ERROR_KIND_UNAVAILABLE\x10\x04\x12\x17\n" +
	"\x13ERROR_KIND_INTERNAL\x10\x05B4Z2github.com/garm-ai/garm-ai/garm/invoke/v1;invokev1b\x06proto3"

var (
	file_garm_invoke_v1_error_proto_rawDescOnce sync.Once
	file_garm_invoke_v1_error_proto_rawDescData []byte
)

func file_garm_invoke_v1_error_proto_rawDescGZIP() []byte {
	file_garm_invoke_v1_error_proto_rawDescOnce.Do(func() {
		file_garm_invoke_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_invoke_v1_error_proto_rawDesc), len(file_garm_invoke_v1_error_proto_rawDesc)))
	})
	return file_garm_invoke_v1_error_proto_rawDescData
}

var file_garm_invoke_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_garm_invoke_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_garm_invoke_v1_error_proto_goTypes = []any{
	(ErrorKind)(0), // 0: garm.invoke.v1.ErrorKind
	(*Error)(nil),  // 1: garm.invoke.v1.Error
}
var file_garm_invoke_v1_error_proto_depIdxs = []int32{
	0, // 0: garm.invoke.v1.Error.kind:type_name -> garm.invoke.v1.ErrorKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_garm_invoke_v1_error_proto_init() }
func file_garm_invoke_v1_error_proto_init() {
	if File_garm_invoke_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_invoke_v1_error_proto_rawDesc), len(file_garm_invoke_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garm_invoke_v1_error_proto_goTypes,
		DependencyIndexes: file_garm_invoke_v1_error_proto_depIdxs,
		EnumInfos:         file_garm_invoke_v1_error_proto_enumTypes,
		MessageInfos:      file_garm_invoke_v1_error_proto_msgTypes,
	}.Build()
	File_garm_invoke_v1_error_proto = out.File
	file_garm_invoke_v1_error_proto_goTypes = nil
	file_garm_invoke_v1_error_proto_depIdxs = nil
}
